### ISSUE TITLE
Does it support messages to/from the inbox of pages?

### ISSUE THREAD

**Issue by dpriskorn** [Senth/facebook-cli#1]

**Comment by Senth** [comment]
Hi, unfortunately not.

You're free to add a pull request if you want to support that feature.

However, note that using facebook-cli violates against the Facebook Terms and Services (since it uses a bot to login, post etc).

Using it once in a while is probably okay, but using it for business to post lots of messages you might want to use an officially supported app for that.

**Comment by dpriskorn** [comment]
Do you know any? Please state clearly in the readme that it violates the terms.

**Comment by Senth** [comment]
You probably have found an app already. I don't know if any app can send messages automatically (I think FB doesn't want to spam its users. The only one I know of is Buffer, but that's to schedule posts. I don't know of any bot-like app.

Closing the issue, as I've updated the README that using this violates the terms.
